### ISSUE TITLE
Updated Emojis? Recent Emojis?

### ISSUE THREAD

**Issue by JCsplash** [isaced/ISEmojiView#11]
Hi! ISEmojiView has been great! Is there any way you could update the emojis? iOS came out with a lot of new emojis and it would be super if you could include those as well.

Also is there anyway to see the recent emojis in the first screen?

**Comment by isaced** [comment]
All emoji stored in [/Source/Assets/ISEmojiList.plist](https://github.com/isaced/ISEmojiView/blob/master/Source/Assets/ISEmojiList.plist), you can update it.

Recent emojis, Planning to add this feature, Welcome to contribute PR.

**Comment by srameshr** [comment]
@isaced Also could you add recent emojis and emoji search?

**Comment by jeffreality** [comment]
I just submitted a PR with all of the latest emojis. This fall, another 150 are going to be added, so this will be an ongoing support issue.

**Comment by jeffreality** [comment]
@isaced Can you make a new release so I can pull this into my app with Cocoapods?

**Comment by srameshr** [comment]
@isaced Also, emoji search and recently used emojis?

**Comment by isaced** [comment]
@srameshr  It's very busy recently, this feature will be a bit later.

**Comment by srameshr** [comment]
I don't mean to push you, but within first week of Aug?
