### ISSUE TITLE
Xcode 10 Beta 3

### ISSUE THREAD

**Issue by ibrahimtall** [isaced/ISEmojiView#16]
Hi.
I don't know if you've run this on Xcode 10 beta 3 but I am getting an error

'UIEdgeInsetsInsetRect' has been replaced by instance method 'CGRect.inset(by:)'

in the ISEmoji.swift file

**Comment by abhuzz** [comment]
In Swift 4.2 defination is changed like: 
```
let container = CGRect(x: 0, y: 0, width: 100, height: 100)
let margin = UIEdgeInsets(top: 10, left: 10, bottom: 10, right: 10)
let customeframe = container.inset(by: margin)
```
