### ISSUE TITLE
Cannot click button on text input bar when emojiView is visible.

### ISSUE THREAD

**Issue by junestchick** [isaced/ISEmojiView#21]
Hi, i am creating a chat VC and it has an input text bar includes a send button and a textview with inputView is ISEmojiView.
The problem is when EmojiView is visible, the emoji button and send button is notclickable. 
Can you help me? Thanks. 
![image](https://user-images.githubusercontent.com/16408328/43817084-f593f932-9b01-11e8-9734-0c211ad413dd.png)

**Comment by isaced** [comment]
Can you upload a demo to show this problem?

**Comment by junestchick** [comment]
As you see, i press emoji button to switch to emoji keyboard, but cannot switch back. The button implements: 
`inputTextView.inputView = isShowEmoji ? emojiView : nil`
`inputTextView.reloadInputViews()`
I think maybe these buttons was covered by something when emoji view is showing. 
https://streamable.com/8ineg

**Comment by isaced** [comment]
Can you provide a sample project?

**Comment by Ngsetest** [comment]
I have the same problem

**Comment by yorkwang** [comment]
Same problem here, any solution?

**Comment by isaced** [comment]
Fixed again, thanks for feedback, please try the new version ([0.2.3](https://github.com/isaced/ISEmojiView/releases/tag/0.2.3)).
