### ISSUE TITLE
When added emojiview in textinput view after that my custom view click not working

### ISSUE THREAD

**Issue by pratikmi** [isaced/ISEmojiView#28]
![screen shot 2018-09-19 at 10 56 28 am](https://user-images.githubusercontent.com/7846766/45732686-0e8b5d80-bbfb-11e8-841a-e6ffea6b3ad8.png)

**Comment by isaced** [comment]
Please try the new version

```
pod 'ISEmojiView', '0.1.1'
```

**Comment by pratikmi** [comment]
> Please try the new version
> 
> ```
> pod 'ISEmojiView', '0.1.1'
> ```

Thanks , now working fine

**Comment by pratikmi** [comment]
Hello Iscade,
Working fine but one issue is need to click on twice on topview option so can please let me know what is a solution

**Comment by sheikpunia1** [comment]
how to open emoji on button click in swift4

**Comment by isaced** [comment]
Sorry, I am late.

Fixed now, thanks for feedback, please try the new version ([0.2.3](https://github.com/isaced/ISEmojiView/releases/tag/0.2.3)).
