### ISSUE TITLE
Pod not fetching all files. 

### ISSUE THREAD

**Issue by asifSdSol** [isaced/ISEmojiView#30]
![screen shot 2018-09-28 at 3 28 43 pm](https://user-images.githubusercontent.com/20966923/46203481-5749c180-c333-11e8-9ec8-f59e1f48fe39.png)

**Comment by t2ac32** [comment]
Did you managed to solve this problem?

**Comment by aliexalter** [comment]
I think pod is not downloading all files. I dont have KeyboardSettings class. Xcode says Use of unresolved identifier 'KeyboardSettings'

**Comment by aliexalter** [comment]
i check pod for swift downloads version 0.0.4. I added version 0.1.2 terminal says version not found. Please check podspec file

**Comment by aliexalter** [comment]
This can be fix by typing
`pod 'ISEmojiView','~> 0.1'`

in podfile for swift
