### ISSUE TITLE
Do not work with Swift 4.2

### ISSUE THREAD

**Issue by misterpear** [isaced/ISEmojiView#31]
Does the current version work with the latest Swift version (4.2) ?

**Comment by JoseVigil** [comment]
+1

**Comment by misterpear** [comment]
I see a new commit that fix it (2 days ago) but pod version is not updated yet 😜

**Comment by t2ac32** [comment]
> I see a new commit that fix it (2 days ago) but pod version is not updated yet 😜

Good to know I'll keep track thanks for commenting !

**Comment by isaced** [comment]
OK, Released v0.1.2 to fix this, try it.

**Comment by misterpear** [comment]
Nice work thanks !
