### ISSUE TITLE
iOS 12.1 New Emojis?

### ISSUE THREAD

**Issue by JCsplash** [isaced/ISEmojiView#34]
Would you be willing to adding the new emojis from iOS 12.1? Would very much appreciate it!
![image](https://user-images.githubusercontent.com/16738930/48104729-aae8de00-e202-11e8-871e-fe55c5475302.png)

**Comment by R0uter** [comment]
https://github.com/isaced/ISEmojiView/issues/44#issuecomment-493903494

**Comment by isaced** [comment]
Try the new version v0.2.2.
