### ISSUE TITLE
When added emojiview in textview then not clicking on textview and other button

### ISSUE THREAD

**Issue by manishbd** [isaced/ISEmojiView#36]
When added emojiview in textinput view after that my custom view click not working #28, same issue in repeating in mycase with  latest verison in xcode 10 , i tried to install od 'ISEmojiView', '0.1.1' n but error coming , please resolve my issue as soon as possible

**Comment by isaced** [comment]
Sorry, I am late.

Fixed now, thanks for feedback, please try the new version ([0.2.3](https://github.com/isaced/ISEmojiView/releases/tag/0.2.3)).
