### ISSUE TITLE
iOS 12 UIResponder.keyboardWillChangeFrameNotification，No response

### ISSUE THREAD

**Issue by bangjier** [isaced/ISEmojiView#37]
In the iOS 12，registered UIResponder.keyboardWillChangeFrameNotification，click ABC Button，To switch the keyboard，notification no response，I use the following code:

lazy var emojiView: EmojiView = {
        let keyboardSettings = KeyboardSettings(bottomType: .categories)
        keyboardSettings.countOfRecentsEmojis = 10
        keyboardSettings.needToShowAbcButton = true

        let emojiView = EmojiView(keyboardSettings: keyboardSettings)
        emojiView.translatesAutoresizingMaskIntoConstraints = false
        return emojiView
}()

func showEmojiKeyboard() {
        emojiView.delegate = self
        emojiTextView.inputView = emojiView
        emojiTextView.becomeFirstResponder()
}

extension viewController: EmojiViewDelegate {
    
    func emojiViewDidSelectEmoji(_ emoji: String, emojiView: EmojiView) {
        emojiTextView.insertText(emoji)
    }
    
    func emojiViewDidPressDeleteBackwardButton(_ emojiView: EmojiView) {
        emojiTextView.deleteBackward()
    }
    
    func emojiViewDidPressChangeKeyboardButton(_ emojiView: EmojiView) {
        emojiTextView.inputView = nil
        emojiTextView.keyboardType = .default
        emojiTextView.reloadInputViews()
    }
    
    func emojiViewDidPressDismissKeyboardButton(_ emojiView: EmojiView) {
        emojiTextView.resignFirstResponder()
    }
    
}

**Comment by isaced** [comment]
I think I have fixed this bug, please check it.
