### ISSUE TITLE
Can someone explain this line to me? This ends up throwing a 'null pointer' exception. 

### ISSUE THREAD

**Issue by tpalber** [isaced/ISEmojiView#38]
https://github.com/isaced/ISEmojiView/blob/75dbf0e08215892cb7fcc0e65036777793d83ae1/Source/Classes/Views/EmojiCollectionView/EmojiCollectionView.swift#L121

When the category is 'recent' for this function, I am getting an exception because the above line returns nil.
It's probably because of the following:
Force-unwrap using '!' to abort execution if the optional value contains 'nil'

I am new to Swift and iOS development, so maybe I am just missing something.

Thanks,
Tenzin

**Comment by isaced** [comment]
It should be fixed, please open it again if there are any problems.
