### ISSUE TITLE
First Emoji selection not working

### ISSUE THREAD

**Issue by mohammadrabi** [isaced/ISEmojiView#40]
i have an issue when the pop up appears 
when I select the emoji for the first time it doesn't respond
thats only for the first time , for the second time i select the emoji and didSelectEmoji method is called normally
after reviewing the code and unlock it , i commented these lines in EmojiCollectionView.swift `didSelectItemAt` method line 164

```swift
//        guard emojiPopView.isHidden else {
//            dismissPopView(false)
//            return
//        }
```

And the issue solved
could you please solve this issue from your side
thanks in advance :)

**Comment by isaced** [comment]
May be the same problem as #28 , fixed.
