### ISSUE TITLE
Blank category icons

### ISSUE THREAD

**Issue by grago** [isaced/ISEmojiView#45]
Thanks for this fantastic library. I wanted to report that i am seeing blank category icons. 

I am testing on Swift 5/Xcode 10.2 and iOS 12.

Thanks!

**Comment by isaced** [comment]
Have you tried the new version?

```ruby
pod 'ISEmojiView', '0.2.1'
```

**Comment by grago** [comment]
Sorry for the late reply. I installed via Carthage:

`github "isaced/ISEmojiView"`

Here's a screenshot of what i am seeeing:

![Screen Shot 2019-06-11 at 3 12 55 AM](https://user-images.githubusercontent.com/76729/59247800-eadbcd80-8bf6-11e9-9748-6934041453fd.png)

Should i install over CocoaPods instead? Thanks.

**Comment by isaced** [comment]
Can you try CocoaPods and let me know if any problem.

**Comment by grago** [comment]
I can confirm that, installing via CocoaPods works like a charm. Thanks!

**Comment by thejeff77** [comment]
Same problem here. I guess its a good excuse to setup CocoaPods :( . Any estimate on fix time?

**Comment by isaced** [comment]
Sorry for coming late, I have fixed the problem that the image resource cannot be loaded inside the Framework.

Please try the new version **[v0.2.5](https://github.com/isaced/ISEmojiView/releases/tag/0.2.5)**. let me know if there are still any problems.

**Comment by thejeff77** [comment]
Works like a charm! Thank you sooo much! You can definitely close this as fixed.
