### ISSUE TITLE
Skin Tone emojis don't work when selected from the "recently used" section

### ISSUE THREAD

**Issue by danobrown** [isaced/ISEmojiView#49]
Steps to re-create:
- Launch the emoji keyboard and select a skin tone emoji
- Re-open the keyboard, the skin tone emoji should now be in the recently used section
- Select the skin tone emoji from the recently used section

Expected results: The skin tone emoji to appear after being selected from recently used.

Actual results: The default yellow version of that emoji appears when the skin tone emoji has been selected.

**Comment by tlloydukdev** [comment]
Same issue for me :-(

**Comment by isaced** [comment]
Fixed, thanks for feedback, please try the new version ([0.2.3](https://github.com/isaced/ISEmojiView/releases/tag/0.2.3)).
