### ISSUE TITLE
Longpress states as iOS

### ISSUE THREAD

**Issue by Ankish** [isaced/ISEmojiView#5]
There are different skin tones for the same emoji's on longpress. Currently on longpress only 1 is visible , any possible updates on that ?

**Comment by isaced** [comment]
Yes, I am also considering adding this feature. but now has not thought of a better implementation, I think this is a complex change, data structures, UI, versatility support.

Do you have any ideas?

**Comment by isaced** [comment]
It can be seen that an emoji contains 5 colors, meaning that our [ISEmojiList.plist](https://github.com/isaced/ISEmojiView/blob/master/Source/Assets/ISEmojiList.plist) needs to contain all and group.

```
👏🏿 Unicode: U+1F44F U+1F3FF，UTF-8: F0 9F 91 8F F0 9F 8F BF
👏🏾 Unicode: U+1F44F U+1F3FE，UTF-8: F0 9F 91 8F F0 9F 8F BE
👏🏽 Unicode: U+1F44F U+1F3FD，UTF-8: F0 9F 91 8F F0 9F 8F BD
👏🏼 Unicode: U+1F44F U+1F3FC，UTF-8: F0 9F 91 8F F0 9F 8F BC
👏🏻 Unicode: U+1F44F U+1F3FB，UTF-8: F0 9F 91 8F F0 9F 8F BB
👏 Unicode: U+1F44F，UTF-8: F0 9F 91 8F
```

**Comment by jeffreality** [comment]
I have submitted a pull request with this feature implemented.
