### ISSUE TITLE
How to open Emoji Keyboard on button?

### ISSUE THREAD

**Issue by NikhilGangurde** [isaced/ISEmojiView#52]
Hello, First of all, great repository.
Currently, I am working on chat application and in which I am using emoji keyboard but I have to open emoji keyboard on button click like WhatsApp rather than text view click.
how can I achieve that?

**Comment by isaced** [comment]
If you still have a target UITextView(or UITextField), you can do it like this:

```swift
// Open emoji keyboard
yourTextView.inputView = emojiView
yourTextView.reloadInputViews()

// Switch to default keyboard
yourTextView.inputView = nil
yourTextView.reloadInputViews()

// Or close keyboard
yourTextView.resignFirstResponder()
```

If you don't have a text view, just use EmojiView as a normal UIView.

**Comment by ProKashif** [comment]
Please Update this who i can open emojiKeyboard through a button click
