### ISSUE TITLE
Support Dark Keyboard on iOS 13 when Dark Mode is enabled

### ISSUE THREAD

**Issue by thejeff77** [isaced/ISEmojiView#58]
Keyboard has white background on iOS 13 when in dark mode. 

For reference, if this helps speed up implementation:

```
        if #available(iOS 13, *) {
            if (vc.traitCollection.userInterfaceStyle == .dark) {
                // Make keyboard background dark.
            }
        }
```

**Comment by thejeff77** [comment]
Looks like this is on line 217 of EmojiView.swift

I think something like this will do it:

    private func setupView() {
        if #available(iOS 13, *) {
            backgroundColor = UIColor.secondarySystemBackground
        }
        else {
            backgroundColor = UIColor(red: 249/255.0, green: 249/255.0, blue: 249/255.0, alpha: 1)
        }
    }

Will also have to check the other view classes for equivalent stuffs.

**Comment by isaced** [comment]
Thanks for the ideas @thejeff77 , I pushed some code to the master branch and updated the example, it looks good, please try it.

![image](https://user-images.githubusercontent.com/2088605/72206611-10052700-34cb-11ea-8bd0-51e95863c393.png)

**Comment by thejeff77** [comment]
Wow cool screenshots. Thanks for doing this! You're like 12 hours ahead of me, was gonna do this today. I'll try it out right now. Thanks :)

Tried to add Swift Package Manager to this project but ran into issues. Any help with that would be pretty great. 

I'll report back in a few.

**Comment by thejeff77** [comment]
Works like a charm. Thanks 🥇 

Will close this out after 0.2.6 tag if that works.

**Comment by isaced** [comment]
Released [v0.2.6](https://github.com/isaced/ISEmojiView/releases/tag/0.2.6)

**Comment by thejeff77** [comment]
You're the best. Thanks.

**Comment by iWeslie** [comment]
The Pod is not updated yet. Please help.   
```
-> Installing ISEmojiView (0.2.6)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/isaced/ISEmojiView.git
     /var/folders/l6/8nk8j_9j02dggl3_0hl29x_40000gn/T/d20200330-14308-g32s22 --template= --single-branch --depth 1 --branch
     0.2.5
     Cloning into '/var/folders/l6/8nk8j_9j02dggl3_0hl29x_40000gn/T/d20200330-14308-g32s22'...
     Note: switching to 'cd7fdd9be435b9545ca0d9a08c5e02dbcb8cc603'.

```

<img width="742" alt="Screen Shot 2020-03-30 at 11 23 38 PM" src="https://user-images.githubusercontent.com/12584632/77930448-7d13a600-72dd-11ea-96d6-d152d4bf45d6.png">


@isaced

**Comment by dustfire** [comment]
hey guys this is not working on iOS14 / latest pod version.
