### ISSUE TITLE
Please Update this who can i open emojiKeyboard through a button click

### ISSUE THREAD

**Issue by ProKashif** [isaced/ISEmojiView#59]
Please Update this how can i open emojiKeyboard through a button click

_Originally posted by @ProKashif in https://github.com/isaced/ISEmojiView/issues/52#issuecomment-557059498_

**Comment by isaced** [comment]
**ISEmojiView** just like a view, you can control it like an `UIView`.

Or I guess your question is "How to pop up the keyboard via a button?"

- [It is possible to show keyboard without using UITextField and UITextView iphone app?](https://stackoverflow.com/questions/13005969/it-is-possible-to-show-keyboard-without-using-uitextfield-and-uitextview-iphone)
- [Force keyboard to show up via button (iOS)](https://stackoverflow.com/questions/2750445/force-keyboard-to-show-up-via-button-ios)

hope this helps.

**Comment by dortest** [comment]
I'm also having the same issue.
I want to show the view as an independent view, I don't want to use a keyboard or textview.
When trying by `using self.view.addSubview(emojiView)`, The view for some reason gets a rect size of (64.0, 49.0), no matter if I give it a frame manually.
And ideas?

**Comment by isaced** [comment]
@dortest If you want to operate the EmojiView as a normal view, I try the following code and it works:

```
let view = EmojiView()
view.frame = CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: 300)
self.view.addSubview(view)
```
