### ISSUE TITLE
Doesn't build in XCode 12 Swift 5.3

### ISSUE THREAD

**Issue by thejeff77** [isaced/ISEmojiView#64]
Anyone else getting this?  ... the last line of the log is ** BUILD SUCCEEDED **

******* Error *********
> carthage update --platform iOS

*** Building scheme "ISEmojiView" in ISEmojiView.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /var/root/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/ISEmojiView/0.2.6/Build/Intermediates.noindex/ArchiveIntermediates/ISEmojiView/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ISEmojiView.framework/ISEmojiView /var/root/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/ISEmojiView/0.2.6/Build/Products/Release-iphonesimulator/ISEmojiView.framework/ISEmojiView -output /Users/userreportingissuenow/Projects/practicePlayer/Carthage/Build/iOS/ISEmojiView.framework/ISEmojiView

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.jNHiqP.log

**Comment by isaced** [comment]
Tried the carthage compilation and it works, do you still have this problem?

```
carthage update --use-xcframeworks


*** Cloning ISEmojiView
*** Checking out ISEmojiView at "0.3.1"
*** xcodebuild output can be found in /var/folders/g3/qz28fs9j3kl25hbtdq5rv62m0000gn/T/carthage-xcodebuild.cYhKLV.log
*** Building scheme "ISEmojiView" in ISEmojiView.xcodeproj
```


```
tree Carthage -L 3
Carthage
├── Build
│   ├── ISEmojiView.xcframework
│   │   ├── Info.plist
│   │   ├── ios-arm64_armv7
│   │   └── ios-arm64_i386_x86_64-simulator
│   └── iOS
│       ├── 11896A29-8F66-3EEF-8B21-6D1411E1C927.bcsymbolmap
│       ├── 6C2D9D1B-5B85-3074-8F25-8B3150F6D0FC.bcsymbolmap
│       └── ISEmojiView.framework
└── Checkouts
    └── ISEmojiView
        ├── CHANGELOG.md
        ├── Example
        ├── ISEmojiView
        ├── ISEmojiView.podspec
        ├── ISEmojiView.xcodeproj
        ...
12 directories, 12 files
```

**Comment by isaced** [comment]
It's closed, if you still encounter any problems, please feel free to reopen.
